### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by pl4yradam** [thecodrr/fdir#33]
Will this package ever have typescript support?

```
depends on 'fdir'. CommonJS or AMD dependencies can cause optimization bailouts.
```

**Comment by thecodrr** [comment]
I haven't tried converting this to TypeScript as there's no reason to because there's already the `index.d.ts` file for type definitions and I don't have in mind to use any feature from TypeScript. Furthermore, I think that writing this in TypeScript might bring the performance down. Haven't tried it so can't be sure.

You are welcome to give it a try and if the performance remains the same or gets better, I might even merge it. I have no plans to bring TypeScript myself though.

_Support for Deno might be in the plans._

**Comment by pl4yradam** [comment]
I understand. I will scrap the warnings that i get. It would be good if you
can test the typescript equivilant. However because its compiled as
commonjs it wont be seen as es standard.

**Comment by thecodrr** [comment]
It seems to me to be a lot of work for little benefit. At the end of the day, the code that is going to run on the Engine is still Javascript. I have carefully hand optimized each part of the code for maximum performance.

If I have extra time, I will surely look into it but no promises.

**Comment by papb** [comment]
I am not sure what is the issue here, the fact that `index.d.ts` already exists should be enough for most purposes... @pl4yradam can you be more clear on what is the issue you are facing?

**Comment by thecodrr** [comment]
Closing this as it seems unnecessary for now. If anyone thinks TypeScript can improve `fdir` in some way, feel free to comment below and I will reopen the issue.
